name: ci-wf 
on: 
  push:
    branches: 
      - develop
  pull_request: 
    branches:  
      - develop
jobs: 
  build_job: 
    runs-on: ubuntu-latest
    steps: 
      - name: welcome steps
        run: echo "welcome to GH actions"
      - name: checkout repository
        uses: actions/checkout@v4  

      
    
